version: '3.9'

services:
  nginx:
    build: frames/nginx
    image: registry.cn-hangzhou.aliyuncs.com/alexlayton/monolab-nginx-latest:1.0
    labels:
      monolab.frame.type: "tool"
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_PORT=80
    volumes:
      - ./sandbox/html:/workdir/html
