version: '3.9'

services:
  phpcli:
    build: frames/php/fpm
    image: alexlayton/monolab-php-cli:1.0
    container_name: alexlayton_monolab_php_cli
    labels:
      monolab.frame.type: "language"
      monolab.frame.lang: "php"
